<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIMTV0sJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIMTV0sJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIMTV0sJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIMTV0sJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIMTV0sJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'IMTV0sJ',
    'container.build_id' => '98c61edc',
    'container.build_time' => 1588887615,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIMTV0sJ');
