<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLcr89dG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLcr89dG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLcr89dG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLcr89dG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLcr89dG\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lcr89dG',
    'container.build_id' => 'c74e2224',
    'container.build_time' => 1589303591,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLcr89dG');
